### ISSUE TITLE
Total numbers for the US

### ISSUE THREAD

**Issue by apaleyes** [TheEconomist/covid-19-excess-deaths-tracker#1]
First of all, thanks for your work, this is fantastically timely dataset release!

Now, to the question. Most countries that have regional data also have a total country numbers. Which is very convenient to consume: just look for the rows where `CountryName == Region`. However I've noticed that United States files dont't have that, only state-level data. Is it possible to also add total US rows?

Thanks!

**Comment by sondreus** [comment]
This has been added some time ago, sorry for the late reply. Thanks!
