### ISSUE TITLE
What, no age-group aspect in prognosis?

### ISSUE THREAD

**Issue by ErikYkema** [TheEconomist/covid-19-excess-deaths-tracker#15]
I think there is a big flaw in predicting excess death following per your methodology as presented here.
One needs to include some age-group buckets (e.g. 0-65, 65-80, 80+ at least), and also track the growth of those, and then rework that in a weighted prognosis. As the mortality rates per bucket are significantly different, and the buckets sizes redistribute quickly with the rapid demographic changes, this cannot be ignored if one wants to make a relevant baseline, and hence relevant excess death estimate.
I conclude that you do it without, as there is no mention on age buckets in the readme, and the e.g. the Netherlands data file is just the totals per year.

**Comment by sondreus** [comment]
Hi Erik, we provide more details on the methodology on our tracker page, but essentially, this is captured indirectly through modelling expected mortality changes over time using the past 5 years of mortality data. Hope this clarifies.
