### ISSUE TITLE
Question about graph results

### ISSUE THREAD

**Issue by OrsonMM** [TheEconomist/covid-19-excess-deaths-tracker#16]
Hi. 

I am interest to use  the code. I can obtained the data of my country,  all the code run very well with my data. 
But I like do the same iterative images. What library of R used ? And what output file recomend use. 

Thank  you for your work !

**Comment by sondreus** [comment]
Hi, images are made using javascript and svelte. If you would like to make images like this using R, I recommend ggplot2
