### ISSUE TITLE
Argentina data now appears to be available

### ISSUE THREAD

**Issue by sondreus** [TheEconomist/covid-19-excess-deaths-tracker#18]
Appears Argentina data is now available, as helpfully pointed here: https://github.com/TheEconomist/covid-19-the-economist-global-excess-deaths-model/issues/6#issue-988372642

I believe it is already in World Mortality, so could be pulled from there.

**Comment by akarlinsky** [comment]
So is Guatemala, and perhaps others missed by this tracker as well. 
Complete data in WMD is always here: https://github.com/akarlinsky/world_mortality
And we update it about twice-three times a week so it will always also include the latest data (for example Iran where we just updated data up to start of September 2021).

**Comment by sondreus** [comment]
That is great @akarlinsky - thanks v much!

**Comment by sondreus** [comment]
Now added!
