### ISSUE TITLE
Kosovo Data

### ISSUE THREAD

**Issue by Nerdm** [TheEconomist/covid-19-excess-deaths-tracker#19]
Hello!
First and foremost, I want to tell you that I'm new to this, github that is.
There are some suggestions I wanted to make regarding data on Kosovo. 

1. The numbers on mortality which are being used are preliminary, which I suppose are from quarterly bulletins. I asked our NSO and they said so.
2. For official data on mortality prior to 2020, is published on statistical yearbook, which you can download it [here](https://askdata.rks-gov.net/PXWeb/pxweb/en/askdata/askdata__09%20Population__Demography%20and%20Migration__Yearly%20indicators__Deaths/vdekjet05.px/?rxid=c772099f-e5c2-409f-9faa-cc666573d2a0), page 70-71. It's in Albanian but google translate will do the trick. With these official numbers, the expected deaths will align more accurately, corresponding to seasonal trends also.
3. The data for 2020 and 2021 is also preliminary. The official data on all-cause mortality is released, up until July 2021. The problem is, that monthly data for 2020 are not as of yet published, just the total number of deaths.

**Comment by sondreus** [comment]
Thanks for the feedback @Nerdm - sorry I did not see this right away, notification escaped me. I've migrated the issue to our source for this data, let's continue discussion here: https://github.com/akarlinsky/world_mortality/issues/18
