### ISSUE TITLE
Kosovo data revised

### ISSUE THREAD

**Issue by Nerdm** [TheEconomist/covid-19-excess-deaths-tracker#21]
The National Statistics Office released revised data regarding deaths in 2021:

https://askdata.rks-gov.net/PXWeb/pxweb/en/askdata/askdata__09%20Population__Demography%20and%20Migration__Monthly%20indicators__Births,%20deaths,%20marriages%20and%20divorces/tab03.px/table/tableViewLayout1/?rxid=5d6732bd-7bea-4af6-bc41-a6ec1a02e75b

**Comment by Nerdm** [comment]
Given that the data used for calculating expected deaths include only deaths occuring inside of Kosovo, the data for 2021 should also include only those deaths which occured inside of Kosovo.

Current data on 2021 include deaths which occured outside of Kosovo, also.

**Comment by sondreus** [comment]
Now have Kosovo data via WMD, thanks for the data
