### ISSUE TITLE
Kosovo 2020 monthly mortality data published

### ISSUE THREAD

**Issue by Nerdm** [TheEconomist/covid-19-excess-deaths-tracker#22]
The National Statistics Office has finally published the monthly mortality data for 2020, page 23 on the document:

https://ask.rks-gov.net/media/6537/vdekjet-2020.pdf 

![Monthly mortality 2020](https://user-images.githubusercontent.com/90572098/146388914-eb6e99ed-81e9-4b95-a7a3-f7f389bbeafd.png)

**Comment by sondreus** [comment]
We now have Kosovo data via WMD, thanks for sharing
