### ISSUE TITLE
Negative values for covid_deaths

### ISSUE THREAD

**Issue by abedgell** [TheEconomist/covid-19-excess-deaths-tracker#23]
Why are there negative values for "covid_deaths" in the file "all_weekly_excess_deaths.csv"?

**Comment by sondreus** [comment]
Hi @abedgell - these reflect adjustments by governments. You can also see them here: https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Confirmed+deaths&Interval=New+per+day&Relative+to+Population=false&Color+by+test+positivity=false&country=DEU~ESP 

Hope this answers your questions
