### ISSUE TITLE
Excess Deaths

### ISSUE THREAD

**Issue by ryankuhnhenn** [TheEconomist/covid-19-excess-deaths-tracker#7]
As population increases, so will expected deaths, are you applying any growth rate to the expected deaths? 2015 deaths should be less than 2020 deaths, just based on population growth. Taking a five year average also won't account for the general raise in expected deaths. If not applying some growth or forecasting model to the expected deaths, then expected deaths numbers for 2020 will be understated to what an actual expected death average should be.

**Comment by pambros** [comment]
I guess population pyramid should be also taken into account (probably more people > 65 years old in 2020 than in 2015). Especially for this graph "Weekly estimated excess deaths by age group". Is it taken into account in your statistical model?

**Comment by sondreus** [comment]
Hi both, yes, we model changes in expected mortality over time. That means we account for both population change and changes in population age distribution.
