### ISSUE TITLE
United Kingdom incorrectly referred to as Britain

### ISSUE THREAD

**Issue by peter337** [TheEconomist/covid-19-excess-deaths-tracker#8]
In the README, it is explained that stats have been compiled for all of England, Wales, Scotland and Northern Ireland, and have been given the collective name of Britain. This is however incorrect, as Britain would only be correct if Northern Ireland was excluded, but with its inclusion the correct name would be United Kingdom.
Although people in Northern Ireland would identify as 'British', this is more to do with historic cultural reasons and 'UK-ans' sounding awful. Similar to how people from the USA refer to themselves as Americans rather than 'USA-ans' even though America is the continent.
Please refer to this article by Britainica for further information:
https://www.britannica.com/story/whats-the-difference-between-great-britain-and-the-united-kingdom

**Comment by sondreus** [comment]
Hi Peter, 

We follow The Economist's style guide on this (which has a 'Britain' section etc). Hope that clarifies and sorry for the late reply.
