### ISSUE TITLE
week numbers and days mismatch 

### ISSUE THREAD

**Issue by Charlie808** [TheEconomist/covid-19-excess-deaths-tracker#9]
Hello! First: great project! 
There seems to be a mismatch between dates and week numbers. For example, for Austria week 8 is between 17-02-20 and 23-02-20, while for Belgium it is between 24-02-20 and 01-03-20. So week 8 for Belgium corresponds to week 9 for Austria. There seems to be different instances of this problem.
All the best,
Carlo

**Comment by sondreus** [comment]
Hi Carlo. Some countries have different weeks - I've just rewritten the repo to account for this. The countries you pointed out are now all harmonized.
